### ISSUE TITLE
Remove compiled files

### ISSUE THREAD

**Issue by domoritz** [journalovi/2023-park-gatherplots#9]
The copied files (e.g. index.html) should probably be removed from the repo as they are generated from the source files and are making it harder to merge changes.

**Comment by mjskay** [comment]
We discussed this previously, and came to the conclusion that including `index.html` (despite it being a generated file) is helpful for several reasons:

- We support non-quarto submissions; having a standard location of the actual paper makes it easier to support a range of document generators (including ones we can't run).
- Having a compiled version gives us a comparison doc we can use to verify correctness of our own compilation.
- Having a compiled version in the repo is better for long-term archiving, since one can (e.g.) use a service like Zenodo to get a long-term archived version of the main branch of the repo, including the rendered paper. Such archives are likely to last longer than our ability to run quarto.

It shouldn't make merge conflicts that hard to deal with as conflicts should only arise if you can generate the file, and if you can generate the file you don't need to resolve conflicts on it (since you can just clobber and re-generate).

Happy to entertain suggestions for a better approach, but on balance I prefer leaving `index.html` in atm.

**Comment by domoritz** [comment]
Thanks for the details of the discussion. Another option is to keep only source files in the main branch and have the compiled files in a GitHub pages branch? Or require automatic builds with GitHub actions for all commits. 

One issue with the current approach is that updates are manual and therefore the compiled file could be out of sync with the source files.

**Comment by mjskay** [comment]
Yeah, we use a github pages branch for the rendered version on the website, which ensures at least that is in sync. 

Unfortunately archiving services like Zenodo only take the main branch, so I'm not sure that works in those cases. I'm going to move this issue over to the template repo (here: https://github.com/journalovi/jovi-template-quarto/issues/9) and we can revisit it after we have more experience with non-Quarto submissions (which should happen when Info+ and VISxAI submissions come in).
